language: minimal
sudo: required
services:
  - docker
before_script:
  - tag="${TRAVIS_TAG:-latest}"
  - image_name="$(echo "${TRAVIS_REPO_SLUG}" | cut -d '/' -f 2)"
  - docker_org="actions"
script: .travis/build.sh $docker_org $tag
before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
deploy:
  - provider: script
    script: .travis/deploy.sh $docker_org $tag
    on:
      branch: master
  - provider: script
    script: .travis/deploy.sh $docker_org $tag
    on:
      branch: master
      tags: true
env:
  - JAVA_VERSION=8u181 JAVA_PACKAGE=server-jre JAVA_SHA256_SUM=678e798008c398be98ba9d39d5114a9b4151f9d3023ccdce8b56f94c5d450698 BUILD_ARGS="JAVA_VERSION JAVA_PACKAGE JAVA_SHA256_SUM" BUILD_PATH=8
  - JAVA_VERSION=8u181 JAVA_PACKAGE=jdk JAVA_SHA256_SUM=1845567095bfbfebd42ed0d09397939796d05456290fb20a83c476ba09f991d3 BUILD_ARGS="JAVA_VERSION JAVA_PACKAGE JAVA_SHA256_SUM" BUILD_PATH=8
  - JAVA_VERSION=10.0.2 JAVA_PACKAGE=serverjre JAVA_SHA256_SUM=4ca492e0dd46c51bb3263d7347f6ede04fceb07fde3f01fed2c0336b18596c41 BUILD_ARGS="JAVA_VERSION JAVA_PACKAGE JAVA_SHA256_SUM" BUILD_PATH=10
  - JAVA_VERSION=10.0.2 JAVA_PACKAGE=jdk JAVA_SHA256_SUM=6633c20d53c50c20835364d0f3e172e0cbbce78fff81867488f22a6298fa372b BUILD_ARGS="JAVA_VERSION JAVA_PACKAGE JAVA_SHA256_SUM" BUILD_PATH=10
  - JAVA_VERSION=11.0.1 JAVA_PACKAGE=jdk JAVA_SHA256_SUM=e7fd856bacad04b6dbf3606094b6a81fa9930d6dbb044bbd787be7ea93abc885 BUILD_ARGS="JAVA_VERSION JAVA_PACKAGE JAVA_SHA256_SUM" BUILD_PATH=11